INSERT INTO CUSTOMER_ENTITY (ID, CLIENT_ID, EMAIL, NAME, SURNAME)
VALUES ('1', 'uuid1', 'tom@gmail.com', 'tom', 'bie');

INSERT INTO CUSTOMER_ENTITY (ID, CLIENT_ID, EMAIL, NAME, SURNAME)
VALUES ('2', 'uuid2', 'gunia@gmail.com', 'gunia', 'biel');

INSERT INTO LOCKER_ENTITY (ID, CITY, LOCKER_ID, SPACE)
VALUES ('1', 'JAWORZNO', 'uuid1', 0);

INSERT INTO LOCKER_ENTITY (ID, CITY, LOCKER_ID, SPACE)
VALUES ('2', 'KATOWICE', 'uuid2', 10);

